### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by wendorf** [tygari/EVO-Idle#2]
It would be great to have a README.md in the root directory so people can learn about this project.

**Comment by tygari** [comment]
I am still learning how to use github,  I only just figured out how to upload a folder.
What exactly should I put in a readme file?

**Comment by wendorf** [comment]
At a minimum, the README should include a short project description and a link to the latest playable version of the game. If you'd like people to contribute to the codebase, you might want to add a short description of how the project is set up and what the plans for the future are, though information for contributors can also go in CONTRIBUTING.md.

mattiassingers has a good list of [awesome readmes](https://github.com/matiassingers/awesome-readme) you can use as inspiration, though many of these are quite long compared to what you'll want to get started.

**Comment by tygari** [comment]
I will see about adding a title readme file.
Thank you.

In the folder is a notes document that holds all my notes on the project.  It is not the most comprehensive of pages but I felt something on my notes was better than nothing.

I am more concerned about my files being readable.  I need to learn better code structure for readability.

**Comment by tygari** [comment]
I have added a readme file.
Hope this is good enough.

**Comment by wendorf** [comment]
Thanks! Looks good to me. I'll close this issue now.
